package com.athletedata.app.data.model

/**
 * Identifies who wrote a row into the database.
 *
 * Used as a discriminator on every sensor-origin table so the UI can label
 * data appropriately and seeder rows can be purged without touching real data.
 */
enum class DataSource {
    DEVICE,  // written by the BLE device driver
    MANUAL,  // entered by the user
    SEEDER,  // generated by the debug dummy-data seeder
}
