package com.athletedata.openAthleteMetrics.data.db

import androidx.room.Dao
import androidx.room.Delete
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import com.athletedata.openAthleteMetrics.data.model.DataSource
import kotlinx.coroutines.flow.Flow
import java.time.Instant
import java.time.LocalDate

@Dao
interface SleepSessionDao {

    // ── Writes ────────────────────────────────────────────────────────────────

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insert(entity: SleepSessionEntity)

    @Insert(onConflict = OnConflictStrategy.IGNORE)
    suspend fun insertOrIgnore(entity: SleepSessionEntity): Long

    /**
     * Extends an existing session's recorded span in place (same row id) — used when new
     * stage rows for a driver+date attach to a session created by an earlier, partial
     * promote() call, so `duration_minutes` doesn't go stale relative to the accumulated
     * stage minutes. Deliberately a raw UPDATE rather than an insert-replace: REPLACE would
     * conflict on the (driver_id, date) unique index, delete the row, and re-insert it under
     * a NEW autogenerated id — cascade-deleting every [SleepStageEntity] already attached to
     * the old id via its foreign key.
     */
    @Query(
        """
        UPDATE sleep_sessions
        SET sleep_start_ms = :startMs, sleep_end_ms = :endMs, duration_minutes = :durationMinutes
        WHERE id = :id
        """
    )
    suspend fun updateSpan(id: Long, startMs: Instant, endMs: Instant, durationMinutes: Int)

    @Delete
    suspend fun delete(entity: SleepSessionEntity)

    /** Deletes all sessions from a specific source; used for seeder cleanup. */
    @Query("DELETE FROM sleep_sessions WHERE source = :source")
    suspend fun deleteBySource(source: DataSource)

    @Query("DELETE FROM sleep_sessions")
    suspend fun deleteAll()

    // ── Reads ─────────────────────────────────────────────────────────────────

    /** The session for a given night (keyed by morning date), or null. */
    @Query("SELECT * FROM sleep_sessions WHERE date = :date LIMIT 1")
    fun getSessionForDate(date: LocalDate): Flow<SleepSessionEntity?>

    /** All sessions in the inclusive date range [from, to], oldest first. */
    @Query(
        """
        SELECT * FROM sleep_sessions
        WHERE date >= :from AND date <= :to
        ORDER BY date ASC
        """
    )
    fun getSessionsForRange(from: LocalDate, to: LocalDate): Flow<List<SleepSessionEntity>>

    /** One-shot read for a specific date; used by DailySummaryWorker. */
    @Query("SELECT * FROM sleep_sessions WHERE date = :date LIMIT 1")
    suspend fun getSessionForDateOnce(date: LocalDate): SleepSessionEntity?

    /** One-shot read for a specific driver + date; used by DeviceSyncProcessor before merge. */
    @Query("SELECT * FROM sleep_sessions WHERE driver_id = :driverId AND date = :date LIMIT 1")
    suspend fun getByDriverAndDate(driverId: String, date: LocalDate): SleepSessionEntity?
}
